steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-west9-docker.pkg.dev/${PROJECT_ID}/fbouy-devops/hello-world', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'europe-west9-docker.pkg.dev/${PROJECT_ID}/fbouy-devops/hello-world']

  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    timeout: 240s
    args: ['compute', 'instances', 
           'create-with-container', 'my-vm-name',
           '--container-image', 
           'europe-west9-docker.pkg.dev/${PROJECT_ID}/fbouy-devops/hello-world']

           
