steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west9-docker.pkg.dev/${PROJECT_ID}/hello-world/hello-world', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west9-docker.pkg.dev/${PROJECT_ID}/hello-world/hello-world']
images: ['europe-west9-docker.pkg.dev/${PROJECT_ID}/hello-world/hello-world']
options:
  logging: CLOUD_LOGGING_ONLY

